#!/usr/bin/env bash
# Bundle the package for upload as a Kaggle Dataset.
#
#   bash scripts/package_for_kaggle.sh
#   -> dist/hangman-src.zip
#
# Upload that zip as a PRIVATE Kaggle Dataset named "hangman-src", then attach
# it to the notebook. The notebook stays thin and imports from it, rather than
# carrying a monolithic paste of the codebase.
#
# Deliberately excludes data/ (competition data is attached separately and must
# not be redistributed) and checkpoints (regenerated by training).
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
cd "$HERE"

rm -rf dist/hangman-src dist/hangman-src.zip
mkdir -p dist/hangman-src

cp -R src dist/hangman-src/src
mkdir -p dist/hangman-src/scripts
for script in build_labels.py build_states.py train.py evaluate.py make_submission.py \
              package_for_kaggle.sh package_data_for_kaggle.sh; do
  cp "scripts/$script" dist/hangman-src/scripts/
done
cp -R tests dist/hangman-src/tests
cp README.md requirements.txt LICENSE dist/hangman-src/
mkdir -p dist/hangman-src/reports
cp reports/kaggle_run.md dist/hangman-src/reports/

find dist/hangman-src -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
find dist/hangman-src -name '*.pyc' -delete 2>/dev/null || true

# Zip from INSIDE the folder: Kaggle extracts the archive directly into
# /kaggle/input/<slug>/, so a wrapper directory would add a pointless level.
cd dist/hangman-src && zip -qr ../hangman-src.zip . && cd ../..
echo "dist/hangman-src.zip  ($(du -h dist/hangman-src.zip | cut -f1))"
echo
echo "Next:"
echo "  1. kaggle.com/datasets -> New Dataset -> upload dist/hangman-src.zip"
echo "     Title: hangman-src   (visibility: Private)"
echo "  2. In the notebook: Add Input -> your dataset + the competition data"
echo "  3. Settings -> Accelerator: GPU T4 x2   |   Internet: OFF"
